create table person(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	fio varchar(100),
	email varchar(100),
	card BIGINT,
	phone BIGINT,
	primary key(id)
);

create table cinema(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	name varchar(30),
	amount_ranks int,
	amount_places_row int,
	primary key(id)
);

create table film(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	name_film varchar(30),
	primary key(id)
);

create table session_film(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	film BIGINT,
	cinema BIGINT,
	time varchar(20),
	price int,
	FOREIGN KEY(film) REFERENCES film(id),
	FOREIGN KEY(cinema) REFERENCES cinema(id),
	primary key(id)
);

create table ticket(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	session_film_id BIGINT,
	row int,
	place int,
	person BIGINT,
	status varchar(20),
	date_creation timestamp,
 	date_change timestamp,
	payment_code BIGINT,
	FOREIGN KEY(person) REFERENCES person(id),
	FOREIGN KEY(session_film_id) REFERENCES session_film(id),
	primary key(id)
);

create table pay(
	payment_code BIGINT GENERATED BY DEFAULT AS IDENTITY,
	summa int,
	card BIGINT,
	status varchar(20),
	primary key(payment_code)
);

select * from person;
select * from cinema;
select * from film;
select * from session_film;
select * from ticket;
select * from pay;

drop table person;
drop table cinema;
drop table film;
drop table session_film;
drop table ticket;
drop table pay;